### ISSUE TITLE
Work around to the sacct vs jobhist output

### ISSUE THREAD

**Issue by dpshelio** [UCL-ARC/hpc-intro#12]
Episode 16 (resources): we need to find a replacement for `bench.snip`, which has the output from the `sacct` command.
* **Hostname** :heavy_check_mark: (`jobhist -h`) 
* **MaxRSS** :heavy_check_mark:(Using `time -v`)
* **Elapsed** :heavy_check_mark: (`jobhist` output `FETIME-FSTIME`)
* **State** :heavy_check_mark: (`jobhist` output)
* **MaxDiskRead** :x:
* **MaxDiskWrite** :x:

The problem with `time` is that the output is quite cryptic for beginners... We may contribute an explanation upstream so it may be also used by others.

**Comment by SJaffa** [comment]
This is updated in the lesson so can close
