### ISSUE TITLE
HPC Carpentry instructions fail for UCL

### ISSUE THREAD

**Issue by dpshelio** [UCL-ARC/hpc-intro#15]
To investigate what may be producing [this error when generating workshops pages](https://github.com/mikerenfro/workshop-2021-09-01/runs/2899352473). However, I kind of "disagree" with building local versions of the repository with our configuration per workshop, instead of using this repository.
Nevertheless, we need to keep the HPC community no hating UCL 😉 

It may be fixed or shown when updating the repository (#8)

**Comment by SJaffa** [comment]
@dpshelio is this fixed in the latest lesson updates or do we still need to investigate this?
