### ISSUE TITLE
Feedback on HPC Intro and HPC Carpentry 

### ISSUE THREAD

**Issue by bkmgit** [UCL-ARC/hpc-intro#23]
Greetings from the [HPC Carpentry](https://github.com/hpc-carpentry) Steering Committee!

We are reaching out to you because this repository is a fork of the [HPC Intro lesson](https://github.com/carpentries-incubator/hpc-intro). The community that maintains your "upstream" repository is currently involved in an effort to become an official lesson program of The Carpentries(tm). We are reaching out to various forks in an effort to identify and build a larger and more integrated HPC Carpentry community.

Part of this process is to show that the upstream lesson is being used, and that there is a pool of potential instructors interested in giving the lesson. This is a big part of showing that there is the scope to grow a wider community around HPC Carpentry.

Is someone from your team is interested in collaborating in this larger community? If so, please indicate yes in this issue. Forks like yours can potentially add value to the broader HPC Carpentry community by expanding the base of instructors, providing feedback on your experience in teaching the material, and providing edits to the material through pull requests or issues, as well as participation in community governance.

**Comment by cdkharris** [comment]
Hello :) Yes, we use this repo to teach a local carpentries-style workshop at UCL. At the moment we are mid-way through bringing this fork up-to-date with the upstream incubator lesson. We are in contact with the maintainers via PRs.

Thanks for checking in! We are invested in the future of this lesson and we're following its progress.
