### ISSUE TITLE
Review the lesson content

### ISSUE THREAD

**Issue by cdkharris** [UCL-ARC/hpc-intro#35]
### Definition of Done / Acceptance Criteria

We recently made a big merge with the upstream repo which includes new content and significant changes to lessons. The new material needs to be checked over to make sure we can use it as-presented on Myriad. The other lessons should also be read, for completeness and my own peace of mind.

[Index](http://github-pages.arc.ucl.ac.uk/hpc-intro/)

Tick off all of these as read; comb more carefully where noted.

- [x] 10
- [x] 11
- [x] 12
- [x] 13
- [x] [14 env variables](http://github-pages.arc.ucl.ac.uk/hpc-intro/14-environment-variables/index.html) Read and test this and make a patch so that the lesson doesn't use my name
- [x] [15 modules](http://github-pages.arc.ucl.ac.uk/hpc-intro/15-modules/index.html) read and perhaps update this
- [x] [16 transferring files](http://github-pages.arc.ucl.ac.uk/hpc-intro/16-transferring-files/index.html) Read and test this
- [x] [17 parallel](http://github-pages.arc.ucl.ac.uk/hpc-intro/17-parallel/index.html) Read and test this
- [x] 18
- [x] 19

**Comment by cdkharris** [comment]
11
- double check host vs system config vars. "For systems like login12.myriad.ucl.ac.uk" should be Myriad
  - (i feel like there was another phrase typo somewhere)
- for us: putty isn't on the "new" d@ua by default. it can be loaded from the ucl application store. this also brings in the accessory apps. then it's in the apps list. exceed is only available on the legacy d@ua.
- typo "the ssh-agent command creates opens a connection" should be either creates or opens or probably just manages.

**Comment by cdkharris** [comment]
12
- update nodetypes output
- update qhost in "Explore..." so it queries a valid node

**Comment by cdkharris** [comment]
13

- correct the second version of `example-job.sh`. the time req as stated will not work with sge

**Comment by cdkharris** [comment]
18

- "Although we covered requesting resources from the scheduler earlier with the π code" is the "pi code" still a relevant reference?
- [this text](http://github-pages.arc.ucl.ac.uk/hpc-intro/18-resources/index.html#stats) is not quite accurate for jobhist, which doesn't report memory usage. I don't think there's anything tidy to do about this.
- correct this [solution](http://github-pages.arc.ucl.ac.uk/hpc-intro/18-resources/index.html#solution): should be `#$ -l h_rt=00:02:00`

**Comment by cdkharris** [comment]
19

- we have a lot of specific resources which could be explained here, but those may have been left off intentionally- i think we rarely make it to this part of the lesson and it mostly re-iterates points that have already been made earlier.

**Comment by cdkharris** [comment]
15 Modules

- thunder slightly stolen because we have stumbled out of the dark ages and now `python3` is just available on the system when you log in.
  - it would work mostly as-written with julia, but then that disturbs the subsequent examples
  - i can make most of the same points with `python --version`
- ansys works with no trouble now. lol.
  - R is ok to sub here
- can happily remove some notes since we updated modules:
  - _Some HPC systems will automatically load dependencies like this, but at the time of writing (June 2020) UCL’s Myriad does not._
  - _(On some systems, this will also unload the modules it depends on. Currently this is not the case with Myriad.)_
- again, matlab default just works now; can do this with R
- fix the format of the time directive for sge

**Comment by cdkharris** [comment]
17 Parallel

- The python install instructions are a good moment to explain about python modules. should be something like

  ```
  module load python/recommended
  module unload compilers mpi
  module load compilers/gnu/4.9.2 mpi4py
  cd amdahl
  python3 -m pip install --user .
  ```

  - check that amdahl winds up on the path
- check that the scripts run
- and replace the output with smth suitable

**Comment by cdkharris** [comment]
14

- Correct the SGE env variables
- Correct the job script

the name thing is sort of ok... doesn't turn up in more than a few lines.

**Comment by heatherkellyucl** [comment]
12: https://github-pages.arc.ucl.ac.uk/hpc-intro/12-cluster/index.html#using-hpc-filesystems is not particularly accurate anymore, not for our systems or (I think) for others. It has been a very long time since we've had separate NFS homes here, and I'm not sure they're actually slower, provided the compute can't write to them. They're recommended for building software, for example...

**Comment by cdkharris** [comment]
> 12: https://github-pages.arc.ucl.ac.uk/hpc-intro/12-cluster/index.html#using-hpc-filesystems is not particularly accurate anymore, not for our systems or (I think) for others. It has been a very long time since we've had separate NFS homes here, and I'm not sure they're actually slower, provided the compute can't write to them. They're recommended for building software, for example...

Agreed- for now I'll say true things in the workshop and i'll keep an eye on what happens to the upstream lesson.
