### ISSUE TITLE
Python example

### ISSUE THREAD

**Issue by dpshelio** [UCL-ARC/hpc-intro#7]
> About the 'Using resources effectively' lesson, which needs a resource-using program to be run: there's also a Python 3 version of calculating pi, if no one has any other Python examples they think would be better. (Would require loading `python3/recommended`). Is in [our pi-examples](https://github.com/UCL-RITS/pi_examples/tree/master/python3_pi_dir) and could be put in `/shared/ucl/apps/examples` like the C one

**Comment by SJaffa** [comment]
The recent lesson update includes [an episode on calculating pi in parallel with Python](http://rits.github-pages.ucl.ac.uk/hpc-intro/16-parallel/index.html). @dpshelio happy to close this issue?

**Comment by SJaffa** [comment]
Closing as this is now in the lesson
